#!/usr/bin/env bash 

echo -e 'Multi-Genre Artists: \n'"$(find . -mindepth 2 -maxdepth 2  -type d | cut -d / -f 3 | sort | uniq -d | while read i; do echo $i ; ls -1Nd */"$i" | cut -f 1 -d / ; done)"
echo -e 'Multi-Disk Albums: \n'"$(find . -mindepth 4 -maxdepth 4 -type d | grep -E 'disk1|Disk1'| cut -d / -f 3 | sort | uniq | while read i ; do echo $i; find -type d|grep "$i"| grep "disk1" | cut -d/ -f 4 | sort ; done)"
echo -e 'Possible Duplicate Albums: \n'"$(find . -mindepth 3 -maxdepth 3 -type d| cut -d / -f 4| sort | uniq -d | while read i; do echo "$i"; find  -mindepth 3 -maxdepth 3 -type d -iname "$i" | cut -d/ -f 2,3 --output-delimiter="    "| sort -k 2 ; done)"
